### ISSUE TITLE
Snap to page when scrolling

### ISSUE THREAD

**Issue by afuhrtrumpet** [CWDG/design-circle-prototype#8]
When put together, the parts of the website should look like this, but with a better transition: http://www.jqueryscript.net/demo/jQuery-Snap-Scrolling-Plugin-For-Single-Page-Website-snapscroll/demo/

**Comment by J3RN** [comment]
We'll also need some jQuery scroll-to-section stuff for the nav bar.

This here plugin does both, but drives me completely insane: http://projects.lukehaas.me/scrollify/#methods

This also does both, but the site is terrible: http://alvarotrigo.com/fullPage/#firstPage

Since this is just for a prototype, I wouldn't worry too hard about these projects being maintained.

**Comment by mrogman** [comment]
fullPage.js has the best transition in my opinion, though they're all a little buggy. It also works with mobile and tablets, which is a plus. We could always develop our own animation if we're not pressed on time. In any case, I agree that this is something we can focus on later.

**Comment by J3RN** [comment]
I'd like to get this user tested - personally I find it infuriating.

Anyhow, fullPage.js broke the navigation bar and only actually displays correctly when you remove

``` CSS
display: table cell
```

for a class called `fp-tableCell`. All this to say that I'm going to try Scollify instead.
